#!/bin/sh
# Run by github/github codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi

# Install some developer tools and setup Linux how I like it
apt-get install -y wget zsh-autosuggestions locate curl


# Setup the database for locate
updatedb

# Install Oh My ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Node
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs

# Install https://github.com/sindresorhus/pure
npm install --global pure-prompt

autoload -U promptinit; promptinit
prompt pure
